apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: add
        path: "/spec/env/-"
        value:
          name: ENVIRONMENT
          value: alpha
    target:
      kind: Application
      name: fint-kontroll-role-pod